<?php

namespace MediaWiki\Extension\Mustache;

use MediaWiki\Parser\Sanitizer;

class MustacheFilters {

	public static function getBuiltinFilters(): array {
		return [
			'css-selector' => static function ( $value ): FilteredString {
				return new FilteredString( preg_replace( '/[^a-zA-Z0-9_.#-]/', '', (string)$value ) );
			},
			'css-value' => static function ( $value ): FilteredString {
				// When a user writes <div style={{test|css-value}}> it will lead to XSS, so we escape =.
				$value = preg_replace( '|[\'":;{}\\\\/<>]|', '', (string)$value );
				$value = str_replace( '=', '&#x3D;', $value );
				return new FilteredString( Sanitizer::checkCss( $value ) );
			},
			'js-string' => static function ( $value ): FilteredString {
				$json = json_encode(
					$value,
					JSON_HEX_TAG | JSON_HEX_APOS | JSON_HEX_QUOT | JSON_HEX_AMP | JSON_UNESCAPED_UNICODE
				);
				return new FilteredString( "'" . substr( $json, 1, -1 ) . "'" );
			},
			'js-identifier' => static function ( $value ): FilteredString {
				return new FilteredString( preg_replace( '/[^a-zA-Z0-9_$]/', '', (string)$value ) );
			},
			'url' => static function ( $value ): FilteredString {
				// Fix urls generated by {{filepath
				if ( str_starts_with( $value, '//' ) ) {
					$value = 'https:' . $value;
				}
				$url = filter_var( $value, FILTER_VALIDATE_URL );
				if ( $url === false ) {
					return new FilteredString( '' );
				}
				$parsed = parse_url( $url );
				$scheme = $parsed['scheme'] ?? '';
				if ( $scheme !== 'http' && $scheme !== 'https' ) {
					return new FilteredString( '' );
				}
				return new FilteredString( $url );
			},
			'attribute' => static function ( $value ): FilteredString {
				$escaped = htmlspecialchars( $value, ENT_QUOTES | ENT_SUBSTITUTE, 'UTF-8' );
				// In case of <div id={{value}}> where value is `something onclick=alert(1)`
				return new FilteredString( str_replace( '=', '&#x3D;', $escaped ) );
			},
		];
	}

	public static function parseInterpolations( string $text ): array {
		$result = [];
		preg_match_all( '/\{\{([^}]+)}}/', $text, $matches );
		foreach ( $matches[1] as $expr ) {
			$filters = array_map( 'trim', explode( '|', $expr ) );
			$varName = array_shift( $filters );
			$result[] = [
				$varName,
				$filters
			];
		}
		return $result;
	}
}
